DATASET:
  imgMaxSize: 700
  imgSizes: (600,)
  list_test: ./data/testing.odgt
  list_train: ./data/training.odgt
  list_val: ./data/validation.odgt
  num_class: 2
  padding_constant: 8
  random_flip: True
  root_dataset: /home/datasets/EgoHands/
  segm_downsampling_rate: 8
DIR: ckpt/egohands-resnet50dilated-ppm_deepsup
MODEL:
  arch_decoder: ppm_deepsup
  arch_encoder: resnet50dilated
  fc_dim: 2048
  weights_decoder: 
  weights_encoder: 
TEST:
  batch_size: 1
  checkpoint: epoch_30.pth
  result: ./results/egohands-resnet50dilated-ppm_deepsup
TRAIN:
  batch_size_per_gpu: 2
  beta1: 0.9
  deep_sup_scale: 0.4
  disp_iter: 20
  epoch_iters: 5000
  fix_bn: False
  lr_decoder: 0.001
  lr_encoder: 0.001
  lr_pow: 0.9
  num_epoch: 30
  optim: Adam
  seed: 304
  start_epoch: 0
  weight_decay: 0.0001
  workers: 8
VAL:
  batch_size: 1
  checkpoint: epoch_30.pth
  visualize: False
